### ISSUE TITLE
Use mirgecom's conda env file for conda packages

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/emirge#111]
instead of the hardcoded list in install-conda-dependencies

**Comment by MTCam** [comment]
This is important because it repairs CI tests for branches that require conda packages that differ from master.  [Like this one that needs Cantera](https://github.com/illinois-ceesd/mirgecom/pull/236).

**Comment by MTCam** [comment]
Should it be *in addition to* the hardcoded list in `install-conda-dependencies`

**Comment by matthiasdiener** [comment]
> Should it be _in addition to_ the hardcoded list in `install-conda-dependencies`?

Imho, no.

**Comment by inducer** [comment]
:shrug: I could go either way.
