### ISSUE TITLE
emirge not compiling on macOS

### ISSUE THREAD

**Issue by dshtey2** [illinois-ceesd/emirge#114]
I have recently installed emirge on a macOS operating system (macOS Big Sur version 11.2), along with the necessary dependencies. When running the example code (`heat-source-mpi.py`), it displays two platforms I can run it on, and with each platform a different issue arises that breaks the code:
- When choosing`Choice [0]: <pyopencl.Platform 'Portable Computing Language' at 0x######>` the code runs through the first few lines, and then fails with the following exception:
```
ld: library not found for -lm
error: linker command failed with exit code 1
```
- When choosing `Choice [1]: <pyopencl.Platform 'Apple' at 0x######>` the code runs through the same first few lines, and then gives me the option of running on CPU or GPU; regardless of which option I take, however, it throws a new error:
```
KeyError: <pyopencl.Context at 0x#### on <pyopencl.Device '(GPU or CPU)' on 'Apple' at 0x####>>

During handling of the above exception, another exception occurred:
...
<program source>: fatal error: 'pyopencl-complex.h' file not found
    #include <pyopencl-complex.h>
                   ^
(options: -I /path/to/file/)
:
system msg for write_line failure : Bad file descriptor
```
This is strange, as the file (`pyopencl-complex.h`) is present in /path/to/file/, so it should be able to find the file.

I have tried multiple fresh installations, including one after deleting my local anaconda installation, but this issue still persists.

Is it perhaps related to #101 ?

**Comment by matthiasdiener** [comment]
> I have recently installed emirge on a macOS operating system (macOS Big Sur version 11.2), along with the necessary dependencies. When running the example code (`heat-source-mpi.py`), it displays two platforms I can run it on, and with each platform a different issue arises that breaks the code:
> 
> * When choosing`Choice [0]: <pyopencl.Platform 'Portable Computing Language' at 0x######>` the code runs through the first few lines, and then fails with the following exception:
> 
> ```
> ld: library not found for -lm
> error: linker command failed with exit code 1
> ```

Yeah, this is a known issue, see here: https://github.com/conda-forge/pocl-feedstock/issues/52

> * When choosing `Choice [1]: <pyopencl.Platform 'Apple' at 0x######>` the code runs through the same first few lines, and then gives me the option of running on CPU or GPU; regardless of which option I take, however, it throws a new error:
> 
> ```
> KeyError: <pyopencl.Context at 0x#### on <pyopencl.Device '(GPU or CPU)' on 'Apple' at 0x####>>
> 
> During handling of the above exception, another exception occurred:
> ...
> <program source>: fatal error: 'pyopencl-complex.h' file not found
>     #include <pyopencl-complex.h>
>                    ^
> (options: -I /path/to/file/)
> :
> system msg for write_line failure : Bad file descriptor
> ```
> 
> This is strange, as the file (`pyopencl-complex.h`) is present in /path/to/file/, so it should be able to find the file.
> 
> I have tried multiple fresh installations, including one after deleting my local anaconda installation, but this issue still persists.
> 
> Is it perhaps related to #101 ?

I think it might not be related to #101. Can you add more info about your system? Which CPU is it? What is your Xcode version, and the version of the Xcode command line tools?

**Comment by dshtey2** [comment]
I have an Intel i5 2.9 GHz Dual-Core CPU, and an Intel Iris Graphics 6100 1536 MB GPU. I am running Xcode version 11.3.1 (11C504) and `xcode-select` version 2384.

**Comment by matthiasdiener** [comment]
> I have an Intel i5 2.9 GHz Dual-Core CPU, and an Intel Iris Graphics 6100 1536 MB GPU. I am running Xcode version 11.3.1 (11C504) and `xcode-select` version 2384.

Did you run `xcode-select --install` ?

**Comment by dshtey2** [comment]
> > I have an Intel i5 2.9 GHz Dual-Core CPU, and an Intel Iris Graphics 6100 1536 MB GPU. I am running Xcode version 11.3.1 (11C504) and `xcode-select` version 2384.
> 
> Did you run `xcode-select --install` ?

Yes, I ran the install command and it said that everything was installed, and I also updated my OS to 11.2.1. Everything is up-to-date now, but I am still getting the same errors.

**Comment by matthiasdiener** [comment]
As a workaround for pocl, you can run the following command in your activated conda environment:

```
$ conda install clang_osx-64
```
