### ISSUE TITLE
Version describer script

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#21]
Make a script whose output describes the state of someone's emirge source tree.

Use cases:

- Include at the beginning of integration test logs to clarify versions
- Student encounters a bug and files an issue
    - So this points to maybe making the output machine-readable (YAML?) to allow easy reproduction?
- Any others?

Info to include per repo:
- `git describe`
- current branch, remote associated with that branch (maybe only if not default)

Since it's possible to screw up the conda env independently of the git checkouts, maybe we should also include information on the state of that. (`conda info` / `pip freeze`)

cc @lukeolson

**Comment by matthiasdiener** [comment]
Should this be a shell script or Python (e.g., to run something  like `from emirge import version; print(version)` ?

**Comment by inducer** [comment]
Good question, I don't know. I was thinking a shell script to keep things simple, but I'm open to other solutions.

**Comment by matthiasdiener** [comment]
> Good question, I don't know. I was thinking a shell script to keep things simple, but I'm open to other solutions.

Ok, I'll write a shell script for now.
