### ISSUE TITLE
Readme assumes that user agrees to ~/.bashrc modification

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#22]
It also assumes that the user is using bash. Neither of those assumptions are valid IMO.

**Comment by matthiasdiener** [comment]
Not clear how it assumes to the bashrc modification, but #27 makes the README independent from bash.

**Comment by inducer** [comment]
> Not clear how it assumes the agreement to the bashrc modification

How else would it know where to find the `conda` command?

Observe that in the [grurdge install docs](https://documen.tician.de/grudge/misc.html), I used an explicit path for `conda create`.

**Comment by lukeolson** [comment]
As a first step I use `source ~/miniconda3/bin/activate`.  Then `conda` is in the path and everything follows.

**Comment by matthiasdiener** [comment]
> It also assumes that the user is using bash. Neither of those assumptions are valid IMO.

As a curiosity, both the Miniforge and Miniconda installation scripts are not compatible with sh, but require bash ;-)

**Comment by inducer** [comment]
> As a first step I use source ~/miniconda3/bin/activate.

IMO that's OK, too. `conda` sorts out "recursive env activation", right?
