### ISSUE TITLE
install-pip-dependencies.sh uses pip install --user

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#25]
It definitely shouldn't. At the very least, that's inconsistent with having created an environment.

**Comment by matthiasdiener** [comment]
The problem is, since `install-pip-dependencies.sh` was requested to be an independent script that does not care about how python was installed, how do we make sure that `pip install` does not fail due to permissions issues?

**Comment by inducer** [comment]
Two points:

* `--user` forcibly circumvents virtualenvs by needlessly dumping stuff into a user-global location. (which is not how `pip install` behaves, which is why at least I would find that surprising/annoying)
* I would consider the pip failure correct behavior: The user hasn't usefully made up their mind on an install location. It's OK to tell them that.
