### ISSUE TITLE
Installation fails on macbook

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/emirge#33]
install.sh fails on my MacBook.  There are no error messages. 

The source of the failure is the silent failure of wget followed by a non-error exit code for install. Adding verbosity to wget invocation in install.sh exposes this error:

> --2020-06-09 10:17:56--https://github.com/condaforge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh
> Resolving github.com (github.com)... 140.82.114.4
> Connecting to github.com (github.com)|140.82.114.4|:443... connected.
> OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
> Unable to establish SSL connection.
> 

This seems to indicate that wget is linked against an version of SSL that is not accepted by the remote host.  Re-installation of wget on my MacBook (via brew) hangs forever and does not install (no error messages since it hangs forever).

**Comment by matthiasdiener** [comment]
Ok, seems like your wget is broken. There isn't much we can do in emirge in this situation. What is your MacOS version? Where did you get wget from?

**Comment by inducer** [comment]
Try `curl`?

**Comment by matthiasdiener** [comment]
I think this was fixed by reinstalling wget.

**Comment by MTCam** [comment]
Indeed, wget (among other things in /usr/local) was (are) dorked up after OS upgrade.  De-wedged the wget re-installation and all is well (after MattD's help).

**Comment by matthiasdiener** [comment]
Closing this issue.
