### ISSUE TITLE
Make default conda prefix a subdirectory of emirge

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#45]
Currently, `./install-conda.sh` will default to `~/miniforge3` as the conda install folder. In an attempt to mess with a user's environment as little as possible, I'd like to propose that we default to a subdirectory of the `emirge` folder, e.g. `conda-root`. @matthiasdiener @lukeolson What do you think?

**Comment by MTCam** [comment]
I know I haven't been asked, but I would like this.

**Comment by MTCam** [comment]
This is done and could be closed. #63
