### ISSUE TITLE
Install additional development tools as part of bootstrapping process

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/emirge#47]
- mpi4py (should be built against system MPI)
- flake8
- pudb
- ipython

**Comment by MTCam** [comment]
Users can also specify custom packages using #67

**Comment by inducer** [comment]
Yeah. I think this is good to close. @matthiasdiener?

**Comment by matthiasdiener** [comment]
Closing, we can reopen if we want to install more tools.
