### ISSUE TITLE
CI status indicator looks inconsistent

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#48]
![image](https://user-images.githubusercontent.com/352067/88402683-171dc380-cd91-11ea-8d18-3c6beec9873a.png)

**Comment by matthiasdiener** [comment]
That's arguably the correct situation. The checkmark at the commit indicates that CI tests passed when PR #42 was merged. On the other hand, all CI tests are failing currently due to the bug exposed by #50. This bug was caused by adding mpi4py to the mirgecom requirements.

**Comment by inducer** [comment]
Huh, ok. Not what I'm used to with Gitlab (the commit status changes based on the latest CI that ran), but I buy that explanation. Thanks!

**Comment by inducer** [comment]
Wait... no.

**Comment by inducer** [comment]
Why should the CI status badge show the state of some x-random PR? Should we restrict that badge to the master branch? (That's what I do in my projects.)

**Comment by matthiasdiener** [comment]
> Why should the CI status badge show the state of some x-random PR? Should we restrict that badge to the master branch? (That's what I do in my projects.)

The badge is already restricted to the `master` branch ( or rather, default branch). The master branch has also been failing, which is why the badge status is 'failing' too. Note that currently all PRs are passing CI, but `master` is not (as the PR that fixes the build has not been merged yet), and the badge is set to 'failing'. 

This is imho the correct behavior.

**Comment by inducer** [comment]
Hmm, OK. Hard to reconstruct now. If I see something that looks off, I'll yell again.

**Comment by inducer** [comment]
Here we go: (note: `branch:master` in query)

![grafik](https://user-images.githubusercontent.com/352067/88980712-e7d3ee80-d289-11ea-95d0-31a77e415d4a.png)

while

![grafik](https://user-images.githubusercontent.com/352067/88980765-020dcc80-d28a-11ea-8d8b-9ee7c65fd6c5.png)

**Comment by matthiasdiener** [comment]
Mine looks like this: 

![image](https://user-images.githubusercontent.com/1772435/88981625-fcb18180-d28b-11ea-9033-222cbf5e5ba7.png)

**Comment by inducer** [comment]
@matthiasdiener Thanks for responding, but I'm not meaning to interrupt your vacation! This is not that urgent...

> Mine looks like this:

I've re-run the master CI since I took my screenshot. (see #52 ) (which produced the failure)

> Last scheduled event also failed: https://github.com/illinois-ceesd/emirge/actions?query=workflow%3A%22CI+test%22+event%3Aschedule+branch%3Amaster

Huh. Is that what it's picking up? If so, I take everything back.

Closing again. Will include scheduled events in my data gathering if I see it happening again.

**Comment by matthiasdiener** [comment]
> @matthiasdiener Thanks for responding, but I'm not meaning to interrupt your vacation! This is not that urgent...

Hehe, no worries. Love looking at these mysteries ;-)

> > Mine looks like this:
> 
> I've re-run the master CI since I took my screenshot. (see #52 ) (which produced the failure)
> 
> > Last scheduled event also failed: https://github.com/illinois-ceesd/emirge/actions?query=workflow%3A%22CI+test%22+event%3Aschedule+branch%3Amaster
> 
> Huh. Is that what it's picking up? If so, I take everything back.
> 
> Closing again. Will include scheduled events in my data gathering if I see it happening again.

Yes, I believe it is also picking up scheduled events, which I think is the correct behavior. What concerns me is that the two pictures we posted above are not the same, ie, disagreeing about the status of that `Install MPI if not already ...` run...

From what I understand, the badge itself shows the last status of a scheduled run or a "pushed" run (ie, whenever a PR gets merged), both applying just to the master branch (implicitly, as that is the default branch). On the other hand, the link when clicking on the badge goes to a list of only "pushed" runs, but to any branch, not only master. This is imho confusing, and we should probably make this more consistent.
My suggestion is to make the badge and link to the master branch, but both pushed and scheduled runs. 

Current: 
`
[![CI test](https://github.com/illinois-ceesd/emirge/workflows/CI%20test/badge.svg)](https://github.com/illinois-ceesd/emirge/actions?query=workflow%3A%22CI+test%22+event%3Apush)
`
[![CI test](https://github.com/illinois-ceesd/emirge/workflows/CI%20test/badge.svg)](https://github.com/illinois-ceesd/emirge/actions?query=workflow%3A%22CI+test%22+event%3Apush)

Suggested:
`
[![CI test](https://github.com/illinois-ceesd/emirge/workflows/CI%20test/badge.svg?branch=master)](https://github.com/illinois-ceesd/emirge/actions?query=branch%3Amaster+workflow%3A%22CI+test%22)
`
[![CI test](https://github.com/illinois-ceesd/emirge/workflows/CI%20test/badge.svg?branch=master)](https://github.com/illinois-ceesd/emirge/actions?query=branch%3Amaster+workflow%3A%22CI+test%22)
