### ISSUE TITLE
Hack requirements.txt parsing to allow not producing a checkout of a package

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#58]
cf. https://github.com/illinois-ceesd/mirgecom/pull/51

**Comment by matthiasdiener** [comment]
In the sense that this line in requirements.txt:

```
git+https:https://github.com/inducer/f2py
```

will not do `git clone` etc. but just run `pip install git+https:https://github.com/inducer/f2py`?

**Comment by inducer** [comment]
Yeah, that was my thought. Maybe recognized via annotation by a special comment:

```
# NOCHECKOUT
git+https://github.com/inducer/f2py.git
```

**Comment by inducer** [comment]
You think that's nuts? Feel free to vent.

**Comment by matthiasdiener** [comment]
Maybe easier to parse:

```
git+https://github.com/inducer/f2py.git # NOCHECKOUT
```

**Comment by inducer** [comment]
Fine by me if that's still a valid (as far as pip is concerned) `requirements.txt` file. I suspect it might not because the hash character can be functional syntax:
```
git+https://github.com/inducer/f2py.git#egg=fparser
```

**Comment by MTCam** [comment]
I like this NOCHECKOUT option, but so far I have just been doing `conda install fparser` to fix the missing fparser.  Is that wrong?

**Comment by matthiasdiener** [comment]
> I like this NOCHECKOUT option, but so far I have just been doing `conda install fparser` to fix the missing fparser. Is that wrong?

The fparser installed from conda is not the same as this: https://github.com/inducer/f2py.git.
