### ISSUE TITLE
Install pymetis from conda-forge

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#76]
- [x] cf. https://github.com/conda-forge/staged-recipes/pull/12448 (i.e. not relevant until that's merged)
- [x] Actually: should wait until it has had the Power9 build enabled. https://github.com/conda-forge/pymetis-feedstock/issues/2

**Comment by inducer** [comment]
https://github.com/conda-forge/pymetis-feedstock/pull/3/ passed and is merged. Should be good to go. (in, like, half an hour... once the production build completes and the CDN updates)

**Comment by matthiasdiener** [comment]
Will installing this pull in mpi4py as well?

**Comment by inducer** [comment]
Nope

**Comment by matthiasdiener** [comment]
What's our plan for installation through conda vs pip?
I considered to only use conda for packages that

- Take a long time to compile or 
- Are difficult to build on our various platforms

As far as I can see, pymetis doesn't really seem to match either of these considerations.

**Comment by inducer** [comment]
My goal is different. Zero from-source installs of C-based packages, other than where stupid vendor MPI forces our hand. Source builds are unreliable.
