### ISSUE TITLE
Install more stuff from conda

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#8]
In #6, @matthiasdiener says:

> I left out creating a new conda environment intentionally, as I assumed we will only use it for the pocl package, if at all.

I disagree. IMO the following things are also needed from Conda:

- If we want to build anything from source: the conda toolchain. I think `conda install compiler` installs that.
- The Python interpreter (I think you get that no mater what)
- `numpy` (otherwise you build from source as a pip dependency or download a binary from pip which may or may not work well)
- `islpy`
- `pyopencl` (We may want to build this from source.)

**Comment by matthiasdiener** [comment]
> I can see your point of view. If you don't think the "unified view" of "conda everywhere" is viable, then we should likely distinguish the use case of "novice installing on laptop" (where IMO conda is hard to beat) from "experienced user installing on DOE machine".

Right, and my idea for `install.sh` was the "novice installing on laptop" case (as well as CI setup). For the "experienced user installing on DOE machine", the README with general instructions might be better.

**Comment by MTCam** [comment]
Could we please have an option to subvert the conda part of install.sh?  Also, it would be good if we can specify where conda is installed.   I do not have, like, or want miniforge in the place where you are hard-coding it.

For my own purposes, on all platforms so far, if I just comment out everything between the top and the PIP line - it works great!  Having a way to do this without editing the file would be terrific - regardless of experience level.

**Comment by matthiasdiener** [comment]
> Could we please have an option to subvert the conda part of install.sh? Also, it would be good if we can specify where conda is installed. I do not have, like, or want miniforge in the place where you are hard-coding it.
> 
> For my own purposes, on all platforms so far, if I just comment out everything between the top and the PIP line - it works great! Having a way to do this without editing the file would be terrific - regardless of experience level.

This was done in #13.
