### ISSUE TITLE
Is emirge impacted by Conda forge Py3.9 version switch?

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/emirge#81]
@matthiasdiener Could you verify that the emirge install still works and does not run into the same issues as outlined in https://github.com/illinois-ceesd/mirgecom/pull/119? (Or, if it does, submit a similar PR here to pin the version?)

**Comment by matthiasdiener** [comment]
Testing it here: https://github.com/illinois-ceesd/emirge/pull/80

**Comment by matthiasdiener** [comment]
Turns out it is impacted.

**Comment by matthiasdiener** [comment]
Fixed by restricting emirge to version 3.8: #80.
